# Generated by Django 4.1.7 on 2023-03-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='state',
            field=models.CharField(choices=[('PT', 'Players turn'), ('WR', 'Winner')], default='PT', max_length=2),
        ),
    ]
